# This is MR pipeline. It must be triggered on every MP commits update.

test-branch-mr:
  extends: .test-branch-template
  stage: Build And Test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
